import type { Tool } from '../types'
import { failure, success } from './helpers'

interface ReadHandleInput {
  handle: string
  offset?: number
  limit?: number
}

const DEFAULT_LIMIT = 8000
const MAX_CHUNK_BYTES = 24_000

export const readHandleTool: Tool<ReadHandleInput> = {
  name: 'read_handle',
  description: '分块读取先前因内容过大而保存的工具结果。仅在上一条工具结果明确出现“Result stored as <实际句柄>”时使用；handle 必须填写该实际句柄（如 mem-...），绝不能填写工具名 read_handle；如仍有内容，使用返回的 nextOffset 继续读取。',
  inputSchema: {
    type: 'object',
    properties: {
      // Handles are generated by MemoryState (`mem-...` on disk,
      // `handle-...` in tests). Reject filesystem paths and tool names before
      // execution so the model gets actionable schema feedback.
      handle: { type: 'string', minLength: 1, pattern: '^(?:mem|handle)-' },
      offset: { type: 'integer', minimum: 0 },
      limit: { type: 'integer', minimum: 1, maximum: DEFAULT_LIMIT },
    },
    required: ['handle'],
  },
  readOnly: true,
  concurrencySafe: true,
  destructive: false,
  requiresConfirmation: false,
  availability: 'always',
  permissions: [],
  async execute(input, ctx, signal) {
    if (signal.aborted) return failure('runtime', '句柄读取已中断', true)
    const requestedHandle = input.handle.trim()
    const handle = requestedHandle === 'read_handle' || requestedHandle === 'handle'
      ? findRecentHandle(ctx.messages)
      : requestedHandle
    if (!handle) {
      return failure(
        'invalid_input',
        'read_handle 的 handle 参数必须是上一条工具结果中显示的实际句柄（例如 mem-...），不能填写工具名 read_handle。请先重新执行产生大结果的原始工具。',
        true,
      )
    }

    const offset = input.offset ?? 0
    const previous = findPreviousRead(ctx.messages, handle, offset)
    if (previous) {
      return failure(
        'loop_detected',
        `已读取句柄 ${handle} 的 offset=${offset}，不要重复读取同一页。请继续使用 offset=${previous.nextOffset} 读取下一段；如果没有下一段，请直接根据已有内容生成结果。`,
        true,
      )
    }

    const content = await ctx.memory.retrieve(handle)
    if (content === null) {
      return failure('not_found', `句柄不存在或已过期：${handle}`, true)
    }

    const limit = input.limit ?? DEFAULT_LIMIT
    const { chunk, count, total } = sliceChunk(content, offset, limit)
    const nextOffset = offset + count < total ? offset + count : undefined

    return success(chunk, {
      handle,
      offset,
      nextOffset,
      total,
    })
  },
  renderCall: (input) => `读取句柄 ${input.handle}（从 ${input.offset ?? 0} 开始）`,
}

/**
 * Detect a repeated page before touching memory again. Tool result metadata is
 * intentionally UI-only, so recover the next offset from the prior tool
 * result's character count and give the model an actionable correction.
 */
function findPreviousRead(
  messages: readonly unknown[] | undefined,
  handle: string,
  offset: number,
): { nextOffset: number } | undefined {
  if (!messages) return undefined
  for (let index = messages.length - 1; index >= 0; index--) {
    const message = messages[index]
    if (!message || typeof message !== 'object') continue
    const parts = (message as { content?: unknown }).content
    if (!Array.isArray(parts)) continue
    for (const part of parts) {
      if (!part || typeof part !== 'object') continue
      const item = part as { type?: unknown; name?: unknown; id?: unknown; input?: unknown }
      if (item.type !== 'tool_use' || item.name !== 'read_handle' || typeof item.id !== 'string') continue
      const input = item.input
      if (!input || typeof input !== 'object') continue
      const args = input as { handle?: unknown; offset?: unknown }
      const previousOffset = typeof args.offset === 'number' ? args.offset : 0
      if (args.handle !== handle || previousOffset !== offset) continue

      for (let next = index + 1; next < messages.length; next++) {
        const resultMessage = messages[next]
        if (!resultMessage || typeof resultMessage !== 'object') continue
        const resultParts = (resultMessage as { content?: unknown }).content
        if (!Array.isArray(resultParts)) continue
        const result = resultParts.find((candidate) => {
          if (!candidate || typeof candidate !== 'object') return false
          const value = candidate as { type?: unknown; tool_use_id?: unknown; is_error?: unknown }
          return value.type === 'tool_result' && value.tool_use_id === item.id && value.is_error !== true
        }) as { content?: unknown } | undefined
        if (typeof result?.content === 'string') {
          // The query loop appends a model-facing pagination hint to the
          // persisted tool result. It is not part of the handle payload and
          // must not inflate the recovered offset.
          const page = result.content.replace(/\n\n\[分页提示\][\s\S]*$/, '')
          return { nextOffset: offset + [...page].length }
        }
      }
    }
  }
  return undefined
}

/** Recover the common model mistake of putting the tool name in `handle`. */
function findRecentHandle(messages: readonly unknown[] | undefined): string | undefined {
  if (!messages) return undefined
  for (let i = messages.length - 1; i >= 0; i--) {
    const message = messages[i]
    if (!message || typeof message !== 'object') continue
    const content = (message as { content?: unknown }).content
    const parts = typeof content === 'string'
      ? [content]
      : Array.isArray(content)
        ? content.flatMap((part) => {
            if (!part || typeof part !== 'object') return []
            const value = (part as { content?: unknown }).content
            return typeof value === 'string' ? [value] : []
          })
        : []
    for (const text of parts) {
      const match = text.match(/Result stored as\s+([^:\s]+)\s*:/i)
      if (match?.[1]) return match[1]
    }
  }
  return undefined
}

function sliceChunk(content: string, offset: number, limit: number) {
  const encoder = new TextEncoder()
  const selected: string[] = []
  let total = 0
  let bytes = 0
  let full = false

  for (const character of content) {
    if (!full && total >= offset && selected.length < limit) {
      const characterBytes = encoder.encode(character).byteLength
      if (bytes + characterBytes <= MAX_CHUNK_BYTES) {
        selected.push(character)
        bytes += characterBytes
      } else {
        full = true
      }
    }
    total++
  }

  return { chunk: selected.join(''), count: selected.length, total }
}
