import { access, mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { load as parseYaml } from 'js-yaml'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const skillsRoot = join(root, 'src/lib/skills/builtin')
const output = join(root, 'src/lib/skills/generated/manifest.ts')

const estimateTokens = (text) => {
  let cjk = 0
  for (const character of text) {
    const code = character.codePointAt(0) ?? 0
    if ((code >= 0x3400 && code <= 0x9fff) || (code >= 0xf900 && code <= 0xfaff)) cjk++
  }
  return Math.ceil(cjk + ([...text].length - cjk) / 4)
}

const fingerprint = (value) => {
  let hash = 0x811c9dc5
  for (let index = 0; index < value.length; index++) hash = Math.imul(hash ^ value.charCodeAt(index), 0x01000193)
  return `skill-${(hash >>> 0).toString(16).padStart(8, '0')}`
}

const entries = []
for (const directory of (await readdir(skillsRoot, { withFileTypes: true })).filter((entry) => entry.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
  const path = join(skillsRoot, directory.name, 'SKILL.md')
  const document = await readFile(path, 'utf8')
  const match = document.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/)
  if (!match) throw new Error(`Missing Skill frontmatter: ${path}`)
  const metadata = parseYaml(match[1])
  if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) throw new Error(`Invalid Skill frontmatter: ${path}`)
  if (metadata.name !== directory.name) throw new Error(`Skill name must match directory: ${path}`)
  if (typeof metadata.description !== 'string' || !metadata.description.trim()) throw new Error(`Skill description is required: ${path}`)
  if (typeof metadata.version !== 'string' || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(metadata.version)) throw new Error(`Invalid Skill version: ${path}`)
  const coreInstructions = document.slice(match[0].length).trim()
  const referenceRoutes = [...new Set([...coreInstructions.matchAll(/(?:`|\()((?:reference|examples|assets)\/[^`\s)]+)(?:`|\))/g)].map((item) => item[1]).filter((route) => route && !/[<>]/.test(route)))]
  for (const route of referenceRoutes) {
    try {
      await access(join(root, 'src/lib/skills/builtin', directory.name, route))
    } catch {
      throw new Error(`Skill reference route does not exist: ${directory.name}/${route}`)
    }
  }
  const allowedTools = [...(metadata['allowed-tools'] ?? [])]
  entries.push({
    metadata: {
      name: metadata.name,
      version: metadata.version,
      description: metadata.description,
      ...(metadata.displayName ? { displayName: metadata.displayName } : {}),
      ...(metadata.icon ? { icon: metadata.icon } : {}),
      ...(metadata.placeholder ? { placeholder: metadata.placeholder } : {}),
      ...(metadata['skip-confirmation'] !== undefined ? { skipConfirmation: metadata['skip-confirmation'] } : {}),
      ...(metadata.author ? { author: metadata.author } : {}),
      ...(allowedTools.length ? { allowedTools } : {}),
      ...(metadata['recommended-models'] ? { recommendedModels: metadata['recommended-models'] } : {}),
      ...(metadata.tags ? { tags: metadata.tags } : {}),
      ...(metadata.stage ? { stage: metadata.stage } : {}),
      source: 'builtin',
      directory: `builtin://${metadata.name}`,
    },
    coreInstructions,
    referenceRoutes,
    allowedTools,
    fingerprint: fingerprint(`${metadata.name}\0${metadata.version}\0${coreInstructions}\0${allowedTools.join(',')}`),
    estimatedTokens: estimateTokens(coreInstructions),
    path: `builtin://${metadata.name}/SKILL.md`,
  })
}

await mkdir(dirname(output), { recursive: true })
await writeFile(output, `/* Generated by scripts/compile-skills.mjs. Do not edit by hand. */\nimport type { CompiledSkill } from '../compiler'\n\nexport const compiledBuiltinSkills: readonly CompiledSkill[] = ${JSON.stringify(entries, null, 2)} as const\n`)
console.log(JSON.stringify({ output: 'src/lib/skills/generated/manifest.ts', skills: entries.length, status: 'pass' }, null, 2))
